name: Build and Deploy

on:
  push:
    branches: [ master,gh-action ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull docker image
      run: docker pull ${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/heads/} || true
    - name: Build docker image
      run: docker build --tag ${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/heads/} .
    - name: Push Docker image
      run: echo docker push ${GITHUB_REPOSITORY,,}:${GITHUB_REF#refs/heads/}
